### ISSUE TITLE
Missing http request to the server

### ISSUE THREAD

**Issue by jurgenhaas** [bushxnyc/sqrl#2]
Hey, this is a good app and helps a lot already to test server side implementations.

Only thing missing seems to be the http request to the server. Here is the command line and output:

```
jurgenhaas@jurgen-ubuntu/v/d/T/s/sqrl> sqrl -d "qrl://d7.localhost/sqrl/login?nut=AimYyr60LZT9QLHwQ4-8bX6MSRzXD7R1DJFdCGG3xUg"
Challenge: qrl://d7.localhost/sqrl/login?nut=AimYyr60LZT9QLHwQ4-8bX6MSRzXD7R1DJFdCGG3xUg&sqrlver=1&sqrlkey=51rwm5wOX6QhZ87zHzSwYYbyigsbf4c3qIpZlNe8Zs4
Domin: "d7.localhost"
SQRLver: 1
SQRLKey: 51rwm5wOX6QhZ87zHzSwYYbyigsbf4c3qIpZlNe8Zs4
SQRLsig: JyeG4eY-W7E-dsylxrNgB3G6HqkbWITOfpo0X-2Iibq46nqltu1Rl8pEgnAKqTMJKpI-sSImXr1Ipjgz8-c7BQ
signature is good
```

It doesn't say anything about it but the server log do not show any request to the expected URL.

**Comment by bushxnyc** [comment]
I've added the HTTP request ouput at the bottom of the debug output. You'll get back the servers response code now.

**Comment by jurgenhaas** [comment]
Perfect, thanks
