### ISSUE TITLE
Revocation feature

### ISSUE THREAD

**Issue by jurgenhaas** [bushxnyc/sqrl#3]
Are you planning to implement the revocation (aka IDLock) from https://www.grc.com/sqrl/idlock.htm into your client? I'm asking because that would be very convenient when developing the whole thing on the server side, the Drupal module in my case.

**Comment by bushxnyc** [comment]
Yes I'm working on the Master met manager at the moment. The idlock implementation details aren't up on the site. I'll start working on that once that is settled.

**Comment by jurgenhaas** [comment]
Great, thanks for the heads up.
